// Generated by CoffeeScript 1.10.0
(function() {
  var $l, React, _, createFactory, d, moment, stores,
    slice = [].slice;

  _ = require('lodash');

  React = require('react');

  d = _.merge(React.DOM, require('./common'), require('./canvas'), require('./containers'));

  createFactory = d.createFactory;

  stores = require('./stores');

  moment = require('moment');

  $l = require('./locale');

  exports.Inbox = createFactory({
    getDefaultProps: function() {
      return {
        store: new stores.InboxStore()
      };
    },
    handleChange: function() {
      return this.forceUpdate();
    },
    componentDidMount: function() {
      this.props.store.on('change', this.handleChange);
      this.props.store.setRestClient(this.props.restClient);
      return this.props.store.init();
    },
    componentWillUnmount: function() {
      return this.props.store.removeListener('change', this.handleChange);
    },
    handleResize: function() {
      return this.forceUpdate();
    },
    handleRemove: function(index, e) {
      var conv;
      e.stopPropagation();
      conv = this.props.store.getItem(index);
      if (confirm($l("deleteMessageConfirmation").replace(/username/, conv.fromProfile.username))) {
        return this.props.store["delete"](conv.fromProfileGuid);
      }
    },
    handleClick: function(index) {
      var conv;
      conv = this.props.store.getItem(index);
      return this.props.onChangePath("/conversation/" + conv.fromProfileGuid);
    },
    renderMessage: function(index, scrollTop) {
      var conv, height, loadingMessage, messageStyle, profile, ref, ref1, ref2, ref3, ref4, text, upgradeToRead, url;
      this.props.store.setScrollTop(scrollTop);
      height = 100;
      conv = this.props.store.getItem(index);
      loadingMessage = d.div({
        style: {
          fontSize: 25,
          padding: 20
        }
      }, "Loading...");
      if ((conv != null ? conv.fromProfile : void 0) == null) {
        return loadingMessage;
      }
      if (!conv.removed) {
        upgradeToRead = ((ref = this.props.features.billing) != null ? ref.available : void 0) && !((ref1 = this.props.features.messaging) != null ? ref1.available : void 0);
      }
      profile = conv.fromProfile;
      if (!(conv != null ? conv.removed : void 0) && (profile.primaryPhoto != null)) {
        url = "" + ((ref2 = profile.primaryPhoto) != null ? ref2.cdnBaseUrl : void 0) + ((ref3 = profile.primaryPhoto) != null ? (ref4 = ref3.urls) != null ? ref4['100x100'] : void 0 : void 0);
      } else {
        url = $l("genericPhotos." + profile.gender);
      }
      text = conv.text;
      if (upgradeToRead) {
        text = $l("messaging.upgradeToRead");
      }
      if (!conv.removed) {
        text = text.replace(/\n/, '');
      }
      if (conv.removed) {
        text = $l("removedProfile");
      }
      messageStyle = {
        height: height - 1,
        position: 'relative',
        backgroundColor: 'white',
        textAlign: 'left',
        overflow: 'hidden',
        width: '100%',
        borderBottom: 'solid 1px black',
        cursor: 'pointer'
      };
      if (conv.removed) {
        messageStyle.backgroundColor = 'rgb(200, 200, 200)';
      }
      return d.div.apply(d, [{
        style: messageStyle,
        onClick: this.handleClick.bind(this, index)
      }].concat(slice.call([
        d.img({
          src: url,
          style: {
            width: 100,
            height: 98
          }
        }, ''), d.span({
          style: {
            position: 'absolute',
            left: 110,
            top: 10,
            color: 'grey',
            fontWeight: 700
          }
        }, profile.username), d.span({
          style: {
            position: 'absolute',
            left: 110,
            top: 50,
            color: 'grey',
            marginRight: "40px"
          }
        }, text), conv.deleted ? d.div({
          style: {
            position: 'absolute',
            left: 0,
            top: 0,
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(150, 150, 150, 0.7)'
          }
        }) : !upgradeToRead ? d.i({
          className: 'fa fa-trash',
          style: {
            fontSize: 20,
            position: 'absolute',
            right: 20,
            top: '50%',
            transform: 'translate(0, -50%)'
          },
          onClick: this.handleRemove.bind(this, index)
        }) : void 0
      ])));
    },
    render: function() {
      return d.div({
        className: 'outer-container'
      }, d.div({
        className: 'inner-container'
      }, d.div({
        className: 'messages-container'
      }, this.props.store.getLoadedCount() === 0 ? this.props.store.isLoading() ? d.div({
        className: 'info-message'
      }, "Loading...") : d.div({
        className: 'info-message'
      }, $l('emptyInbox')) : d.HtmlListView({
        ref: 'listView',
        numberOfItemsGetter: (function(_this) {
          return function() {
            return _this.props.store.getLoadedCount();
          };
        })(this),
        itemHeightGetter: (function(_this) {
          return function() {
            return 100;
          };
        })(this),
        itemGetter: this.renderMessage,
        onClick: this.handleClick
      }))));
    }
  });

  exports.Conversation = createFactory({
    getDefaultProps: function() {
      return {
        store: new stores.ConversationStore()
      };
    },
    handleChange: function() {
      return this.forceUpdate();
    },
    handleViewProfile: function(e) {
      e.preventDefault();
      return this.props.onChangePath("/profile/" + this.props.conversation.conversationWithGuid);
    },
    componentWillMount: function() {
      var conv, ref;
      this.props.store.init(this.props.conversation);
      conv = this.props.store.getConversation(this.props.conversation.conversationWithGuid);
      return this.setState({
        loadedMessages: conv != null ? (ref = conv.messages) != null ? ref.length : void 0 : void 0
      });
    },
    componentDidMount: function() {
      this.props.store.on('change', this.handleChange);
      return this.props.store.setRestClient(this.props.restClient);
    },
    componentWillUnmount: function() {
      return this.props.store.removeListener('change', this.handleChange);
    },
    componentDidUpdate: function() {
      var node;
      if (this.shouldScrollBottom) {
        node = $('body')[0];
        return node.scrollTop = node.scrollHeight;
      }
    },
    render: function() {
      var conv, messages, previousMessage, profile, ref, ref1, ref2, ref3, ref4, ref5, removedMessages, url;
      conv = this.props.store.getConversation(this.props.conversation.conversationWithGuid);
      profile = conv.profileSummary;
      if (profile == null) {
        return d.div({
          className: 'outer-container'
        }, d.div({
          className: 'inner-container',
          style: {
            paddingTop: 20
          }
        }, d.h2({}, $l('removedProfile'))));
      }
      if (profile.primaryPhoto != null) {
        url = "" + ((ref = profile.primaryPhoto) != null ? ref.cdnBaseUrl : void 0) + ((ref1 = profile.primaryPhoto) != null ? (ref2 = ref1.urls) != null ? ref2['100x100'] : void 0 : void 0);
      } else {
        url = $l("genericPhotos." + profile.gender);
      }
      previousMessage = null;
      messages = conv.messages;
      if (!((ref3 = this.state) != null ? ref3.showAllMessages : void 0)) {
        removedMessages = (((ref4 = this.state) != null ? ref4.loadedMessages : void 0) || messages.length) - 3;
        messages = _.takeRight(messages, messages.length - removedMessages);
      }
      return d.div({
        className: 'outer-container conversation'
      }, d.div({
        className: 'inner-container'
      }, d.a({
        onClick: this.handleViewProfile
      }, d.div({
        className: 'profile-summary'
      }, d.div({
        className: "photo " + this.props.className
      }, d.img({
        width: '100%',
        height: '100%',
        src: url
      })), d.div({
        className: "username"
      }, profile.username), d.div({
        className: "info"
      }, d.span({}, profile.age), d.Bullet({}), d.span({}, profile.city || "United States")))), d.div.apply(d, [{
        className: 'messages'
      }, (removedMessages != null) && removedMessages > 0 ? d.Button({
        className: "see-all-messages",
        onClick: (function(_this) {
          return function() {
            return _this.setState({
              showAllMessages: true
            });
          };
        })(this)
      }, "See " + removedMessages + " older messages") : void 0].concat(slice.call(_.map(messages, (function(_this) {
        return function(message) {
          var previousType;
          previousType = previousMessage != null ? previousMessage.type : void 0;
          previousMessage = message;
          return d.div({
            className: "message " + message.type + " " + previousType + "-" + message.type
          }, message.type === 'received' ? d.div({
            className: "photo"
          }, d.a({
            onClick: _this.handleViewProfile
          }, d.img({
            width: '100%',
            height: '100%',
            src: url
          }))) : void 0, d.div({
            className: "text"
          }, message.text), d.div({
            className: "timestamp"
          }, moment.utc(message.timestamp).from(moment())));
        };
      })(this))))), d.div({
        className: "send-message"
      }, d.textarea({
        placeholder: $l('messaging.sendMessagePlaceholder'),
        ref: 'messageText',
        value: (ref5 = this.state) != null ? ref5.message : void 0,
        onChange: (function(_this) {
          return function(e) {
            return _this.setState({
              message: $(e.target).val()
            });
          };
        })(this)
      }), d.Button({
        className: "pill send tiny",
        onClick: (function(_this) {
          return function() {
            return _this.props.store.sendMessage(conv.conversationWithGuid, _this.state.message, function() {
              _this.shouldScrollBottom = true;
              return _this.setState({
                message: ""
              });
            });
          };
        })(this)
      }, "Send"))));
    }
  });

}).call(this);

//# sourceMappingURL=messaging.js.map
